package enumerations;

public enum ECategoriesQoEnfant implements ECategoriesQOs {
	STRUCTURE_FAMILIALE,
	DYNAMIQUE_FAMILIALE,
	ANTECEDENTS_FAMILIAUX,
	CONDITIONS_NATALES,
	DEVELOPPEMENT_PSYCHOMOTEUR,
	DEVELOPPEMENT_LANGAGIER,
	COMPORTEMENT;
}
